import json

lines = []
a = lines.append

a("""import { useState } from 'react';""")
a("""import { PenTool, BookOpen, ChevronDown, ChevronUp, Copy, Check, Send, History, Star, Zap, BarChart3, TrendingUp, Type, ArrowLeft } from 'lucide-react';""")
a("""import { writingTemplates, translationExamples } from '../data/writing';""")
a("""import { useAppStore } from '../store/useAppStore';""")
a("""""")
a("""type TabType = 'writing' | 'translation';""")
a("""type WritingMode = 'view' | 'practice';""")
a("""""")
a("""interface AIReport {""")
a("""  total: number;""")
a("""  vocabulary: number;""")
a("""  grammar: number;""")
a("""  structure: number;""")
a("""  coherence: number;""")
a("""  length: number;""")
a("""  suggestions: string[];""")
a("""}""")
a("""""")
a("""export const Writing = () => {""")
a("""  const [activeTab, setActiveTab] = useState<TabType>('writing');""")
a("""  const [selectedTopic, setSelectedTopic] = useState(0);""")
a("""  const [expandedExample, setExpandedExample] = useState<number | null>(null);""")
a("""  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);""")
a("""  const [writingMode, setWritingMode] = useState<WritingMode>('view');""")
a("""  const [userInput, setUserInput] = useState('');""")
a("""  const [score, setScore] = useState<number | null>(null);""")
a("""  const [showHistory, setShowHistory] = useState(false);""")
a("""  const [aiReport, setAiReport] = useState<AIReport | null>(null);""")
a("""  const [isAnalyzing, setIsAnalyzing] = useState(false);""")
a("""  const { addWritingHistory, writingHistory } = useAppStore();""")
a("""""")
a("""  const handleCopy = async (text: string, index: number) => {""")
a("""    await navigator.clipboard.writeText(text);""")
a("""    setCopiedIndex(index);""")
a("""    setTimeout(() => setCopiedIndex(null), 2000);""")
a("""  };""")
a("""""")
a("""  // Advanced AI scoring engine""")
a("""  const analyzeWriting = (text: string): { score: number; report: AIReport } => {""")
a("""    const words = text.trim().split(/\\s+/).filter(w => w.length > 0);""")
a("""    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0);""")
a("""    const paragraphs = text.split(/\\n\\n+/).filter(p => p.trim().length > 0);""")
a("""    const wordCount = words.length;""")
a("""""")
a("""    // 1. Vocabulary richness (unique words / total words)""")
a("""    const uniqueWords = new Set(words.map(w => w.toLowerCase().replace(/[^a-z]/g, '')));""")
a("""    const richness = wordCount > 0 ? uniqueWords.size / wordCount : 0;""")
a("""    const vocabularyScore = Math.min(20, Math.round(richness * 30 + Math.min(wordCount / 30, 5)));""")
a("""""")
a("""    // 2. Advanced vocabulary detection""")
a("""    const advancedWords = [""")
a("""      'however', 'therefore', 'nevertheless', 'moreover', 'furthermore', 'consequently','"
"""      'significantly', 'substantially', 'predominantly', 'inevitably', 'fundamentally','"
"""      'comprehensive', 'sophisticated', 'phenomenon', 'paradigm', 'hypothesis','"
"""      'implication', 'methodology', 'controversy', 'sustainable', 'infrastructure','"
"""      'accommodate', 'predominant', 'controversial', 'perspective', 'elaborate','"
"""      'acquisition', 'autonomous', 'benchmark', 'collaboration', 'deteriorate','"
"""    ];""")
a("""    const advancedCount = advancedWords.filter(w => """)
a("""      text.toLowerCase().includes(w)""")
a("""    ).length;""")
a("""    const vocabBonus = Math.min(10, advancedCount * 3);""")
a("""""")
a("""    // 3. Transition & connector analysis""")
a("""    const transitions = [""")
a("""      'first', 'second', 'third', 'finally', 'lastly', 'firstly','"
"""      'however', 'moreover', 'furthermore', 'nevertheless', 'nonetheless','"
"""      'therefore', 'thus', 'consequently', 'accordingly','"
"""      'in addition', 'in conclusion', 'in summary', 'on the other hand','"
"""      'for example', 'for instance', 'such as', 'namely','"
"""      'although', 'despite', 'whereas', 'while', 'meanwhile','"
"""      'on the contrary', 'by contrast', 'in contrast', 'in terms of','"
"""      'as a result', 'due to', 'owing to', 'because of',""")
a("""    ];""")
a("""    const lowerText = text.toLowerCase();""")
a("""    const matchedTransitions = transitions.filter(t => lowerText.includes(t));""")
a("""    const transitionScore = Math.min(20, matchedTransitions.length * 4);""")
a("""""")
a("""    // 4. Sentence structure variety""")
a("""    const sentenceLengths = sentences.map(s => s.trim().split(/\\s+/).length);""")
a("""    const avgSentenceLength = sentenceLengths.length > 0 """)
a("""      ? sentenceLengths.reduce((a, b) => a + b, 0) / sentenceLengths.length : 0;""")
a("""    // Ideal: 12-25 words per sentence""")
a("""    let structureScore = 0;""")
a("""    if (avgSentenceLength >= 12 && avgSentenceLength <= 25) structureScore = 15;""")
a("""    else if (avgSentenceLength >= 8 && avgSentenceLength <= 30) structureScore = 10;""")
a("""    else structureScore = 5;""")
a("""    // Bonus for sentence variety (different lengths)""")
a("""    if (sentenceLengths.length > 2) {""")
a("""      const variety = new Set(sentenceLengths.map(l => Math.round(l / 5) * 5)).size;""")
a("""      structureScore = Math.min(20, structureScore + variety * 2);""")
a("""    }""")
a("""""")
a("""    // 5. Paragraph coherence""")
a("""    const coherenceScore = paragraphs.length >= 3 ? 15 : paragraphs.length >= 2 ? 10 : 5;""")
a("""""")
a("""    // 6. Length scoring""")
a("""    let lengthScore = 0;""")
a("""    if (wordCount >= 150) lengthScore = 15;""")
a("""    else if (wordCount >= 100) lengthScore = 12;""")
a("""    else if (wordCount >= 60) lengthScore = 8;""")
a("""    else if (wordCount >= 30) lengthScore = 5;""")
a("""    else lengthScore = 2;""")
a("""""")
a("""    // 7. Common grammar pattern checks""")
a("""    const grammarHints: string[] = [];""")
a("""    // Check for 'there is/are' usage""")
a("""    const therePattern = /there\\s+(is|are|was|were)\\s+/gi;""")
a("""    const thereMatches = text.match(therePattern);""")
a("""    if (thereMatches && thereMatches.length > 3) {""")
a("""      grammarHints.push('建议减少重复使用 \"there is/are\" 句型，尝试更多样的句式');""")
a("""    }""")
a("""    // Check for overly simple sentences""")
a("""    const simpleStarters = ['I think', 'I believe', 'It is', 'This is', 'They are'];""")
a("""    const simpleCount = simpleStarters.filter(s => lowerText.startsWith(s) || lowerText.includes('. ' + s)).length;""")
a("""    if (simpleCount > 3) {""")
a("""      grammarHints.push('可以尝试使用从句和复合句来增强表达深度');""")
a("""    }""")
a("""    // Check for passive voice""")
a("""    const passivePattern = /\\b(is|are|was|were|been|being)\\s+(\\w+ed)\\b/gi;""")
a("""    const passiveMatches = text.match(passivePattern);""")
a("""    if (passiveMatches && passiveMatches.length > wordCount * 0.1) {""")
a("""      grammarHints.push('被动语态使用较多，适当增加主动语态使文章更生动');""")
a("""    }""")
a("""""")
a("""    const grammarScore = Math.max(5, 20 - simpleCount * 3);""")
a("""""")
a("""    // Generate suggestions""")
a("""    if (wordCount < 80) grammarHints.push('文章篇幅较短，建议扩展到100词以上');""")
a("""    if (matchedTransitions.length < 3) grammarHints.push('建议使用更多连接词和过渡短语');""")
a("""    if (paragraphs.length < 2) grammarHints.push('建议将文章分为至少3段：开头、正文、结论');""")
a("""    if (advancedCount < 2) grammarHints.push('可以尝试使用一些高级词汇来丰富表达');""")
a("""""")
a("""    const total = Math.min(100, vocabularyScore + vocabBonus + transitionScore + structureScore + coherenceScore + lengthScore + grammarScore);""")
a("""""")
a("""    return {""")
a("""      score: total,""")
a("""      report: {""")
a("""        total,""")
a("""        vocabulary: Math.min(20, vocabularyScore + vocabBonus),""")
a("""        grammar: grammarScore,""")
a("""        structure: structureScore,""")
a("""        coherence: coherenceScore,""")
a("""        length: lengthScore,""")
a("""        suggestions: grammarHints.length > 0 ? grammarHints : ['写得很好！继续保持'],""")
a("""      },""")
a("""    };""")
a("""  };""")
a("""""")
a("""  const handleSubmitWriting = () => {""")
a("""    if (!userInput.trim()) return;""")
a("""    setIsAnalyzing(true);""")
a("""    // Simulate analysis delay for UX""")
a("""    setTimeout(() => {""")
a("""      const { score: totalScore, report } = analyzeWriting(userInput);""")
a("""      setScore(totalScore);""")
a("""      setAiReport(report);""")
a("""      addWritingHistory({""")
a("""        topic: writingTemplates[selectedTopic]?.topic || '写作练习',""")
a("""        content: userInput,""")
a("""        score: totalScore,""")
a("""      });""")
a("""      setIsAnalyzing(false);""")
a("""    }, 800);""")
a("""  };""")
a("""""")
a("""  const handleSubmitTranslation = () => {""")
a("""    if (!userInput.trim()) return;""")
a("""    setIsAnalyzing(true);""")
a("""    setTimeout(() => {""")
a("""      const example = translationExamples[selectedTopic];""")
a("""      const correctWords = example.english.toLowerCase().split(/\\s+/).filter(Boolean);""")
a("""      const userWords = userInput.toLowerCase().split(/\\s+/).filter(Boolean);""")
a("""      """)
a("""      let matchedWords = 0;""")
a("""      userWords.forEach((word) => {""")
a("""        if (correctWords.includes(word)) matchedWords++;""")
a("""      });""")
a("""      """)
a("""      // Word order similarity (bigram matching)""")
a("""      let bigramMatches = 0;""")
a("""      const userBigrams = userWords.slice(0, -1).map((w, i) => `${w} ${userWords[i + 1]}`);""")
a("""      const correctBigrams = correctWords.slice(0, -1).map((w, i) => `${w} ${correctWords[i + 1]}`);""")
a("""      userBigrams.forEach(bg => { if (correctBigrams.includes(bg)) bigramMatches++; });""")
a("""      """)
a("""      const accuracy = Math.min(100, Math.round((matchedWords / correctWords.length) * 70));""")
a("""      const orderBonus = correctBigrams.length > 0 ? Math.round((bigramMatches / correctBigrams.length) * 30) : 0;""")
a("""      const totalScore = Math.min(100, accuracy + orderBonus);""")
a("""      """)
a("""      setScore(totalScore);""")
a("""      setAiReport({""")
a("""        total: totalScore,""")
a("""        vocabulary: Math.round(accuracy * 0.4),""")
a("""        grammar: Math.round(accuracy * 0.3),""")
a("""        structure: Math.round(orderBonus),""")
a("""        coherence: Math.round(accuracy * 0.2),""")
a("""        length: correctWords.length > 0 ? Math.round((userWords.length / correctWords.length) * 10) : 0,""")
a("""        suggestions: totalScore >= 80 ? ['翻译得很准确！'] : ['对比参考答案，注意关键词汇的搭配'],""")
a("""      });""")
a("""      addWritingHistory({""")
a("""        topic: `翻译：${example.chinese.slice(0, 20)}...`,""")
a("""        content: userInput,""")
a("""        score: totalScore,""")
a("""      });""")
a("""      setIsAnalyzing(false);""")
a("""    }, 600);""")
a("""  };""")
a("""""")
a("""  const handleReset = () => {""")
a("""    setUserInput('');""")
a("""    setScore(null);""")
a("""    setAiReport(null);""")
a("""  };""")
a("""""")
a("""  const scoreColor = (s: number) => {""")
a("""    if (s >= 80) return 'text-green-400';""")
a("""    if (s >= 60) return 'text-yellow-400';""")
a("""    return 'text-red-400';""")
a("""  };""")
a("""""")
a("""  const scoreBg = (s: number) => {""")
a("""    if (s >= 80) return 'from-green-500/20 to-green-600/10';""")
a("""    if (s >= 60) return 'from-yellow-500/20 to-yellow-600/10';""")
a("""    return 'from-red-500/20 to-red-600/10';""")
a("""  };""")
a("""""")
a("""  return (""")
a("""    <div className=\"min-h-screen pb-24 md:pb-0 animate-fade-in-up\">""")
a("""      <header className=\"p-6 mb-6\">""")
a("""        <h1 className=\"text-3xl font-bold text-white mb-4\">写作翻译</h1>""")
a("""        <div className=\"flex gap-2 flex-wrap\">""")
a("""          <button""")
a("""            onClick={() => { setActiveTab('writing'); setWritingMode('view'); setScore(null); setUserInput(''); setAiReport(null); }}""")
a("""            className={`px-4 py-2 rounded-full transition-all ${activeTab === 'writing' ? 'bg-gradient-to-r from-primary-500 to-accent-500 text-white' : 'bg-white/10 text-white/70 hover:bg-white/20'}`}""")
a("""          >""")
a("""            写作模板""")
a("""          </button>""")
a("""          <button""")
a("""            onClick={() => { setActiveTab('translation'); setWritingMode('view'); setScore(null); setUserInput(''); setAiReport(null); }}""")
a("""            className={`px-4 py-2 rounded-full transition-all ${activeTab === 'translation' ? 'bg-gradient-to-r from-primary-500 to-accent-500 text-white' : 'bg-white/10 text-white/70 hover:bg-white/20'}`}""")
a("""          >""")
a("""            翻译练习""")
a("""          </button>""")
a("""          <button""")
a("""            onClick={() => setShowHistory(!showHistory)}""")
a("""            className={`px-4 py-2 rounded-full transition-all flex items-center gap-2 ${showHistory ? 'bg-gradient-to-r from-primary-500 to-accent-500 text-white' : 'bg-white/10 text-white/70 hover:bg-white/20'}`}""")
a("""          >""")
a("""            <History className=\"w-4 h-4\" />历史记录""")
a("""          </button>""")
a("""        </div>""")
a("""      </header>""")
a("""""")
a("""      {showHistory && (""")
a("""        <section className=\"px-6 mb-6\">""")
a("""          <div className=\"glass-card p-6\">""")
a("""            <h3 className=\"text-lg font-bold text-white mb-4\">写作历史</h3>""")
a("""            {writingHistory.length === 0 ? (""")
a("""              <p className=\"text-white/70 text-center py-8\">暂无写作记录</p>""")
a("""            ) : (""")
a("""              <div className=\"space-y-4 max-h-96 overflow-y-auto\">""")
a("""                {writingHistory.slice().reverse().map((item) => (""")
a("""                  <div key={item.id} className=\"bg-white/5 rounded-xl p-4\">""")
a("""                    <div className=\"flex items-center justify-between mb-2\">""")
a("""                      <span className=\"text-white font-medium\">{item.topic}</span>""")
a("""                      <div className=\"flex items-center gap-1\">""")
a("""                        <Star className=\"w-4 h-4 text-yellow-400 fill-yellow-400\" />""")
a("""                        <span className=\"text-yellow-400 font-bold\">{item.score}</span>""")
a("""                      </div>""")
a("""                    </div>""")
a("""                    <p className=\"text-white/70 text-sm line-clamp-2\">{item.content}</p>""")
a("""                    <p className=\"text-white/50 text-xs mt-2\">{new Date(item.timestamp).toLocaleString('zh-CN')}</p>""")
a("""                  </div>""")
a("""                ))}""")
a("""              </div>""")
a("""            )}""")
a("""          </div>""")
a("""        </section>""")
a("""      )}""")
a("""""")
a("""      {activeTab === 'writing' ? (""")
a("""        <section className=\"px-6\">""")
a("""          {writingMode === 'view' ? (""")
a("""            <>""")
a("""              <div className=\"flex gap-2 mb-6 overflow-x-auto pb-2\">""")
a("""                {writingTemplates.map((template, index) => (""")
a("""                  <button key={template.id} onClick={() => setSelectedTopic(index)}""")
a("""                    className={`px-4 py-2 rounded-full transition-all whitespace-nowrap ${selectedTopic === index ? 'bg-gradient-to-r from-primary-500 to-accent-500 text-white' : 'bg-white/10 text-white/70 hover:bg-white/20'}`}""")
a("""                  >{template.topic}</button>""")
a("""                ))}""")
a("""              </div>""")
a("""              <div className=\"grid grid-cols-1 md:grid-cols-2 gap-6\">""")
a("""                <div className=\"glass-card p-6\">""")
a("""                  <h2 className=\"text-xl font-bold text-white mb-4\">常用句型模板</h2>""")
a("""                  <div className=\"space-y-4\">""")
a("""                    {writingTemplates[selectedTopic]?.templates.map((template, index) => (""")
a("""                      <div key={index} className=\"bg-white/5 rounded-xl p-4\">""")
a("""                        <p className=\"text-white font-english italic\">{template}</p>""")
a("""                        <button onClick={() => handleCopy(template, index)}""")
a("""                          className=\"mt-3 flex items-center gap-2 text-white/70 hover:text-white transition-all\">""")
a("""                          {copiedIndex === index ? <Check className=\"w-4 h-4\" /> : <Copy className=\"w-4 h-4\" />}""")
a("""                          {copiedIndex === index ? '已复制' : '复制'}""")
a("""                        </button>""")
a("""                      </div>""")
a("""                    ))}""")
a("""                  </div>""")
a("""                </div>""")
a("""                <div className=\"glass-card p-6\">""")
a("""                  <div className=\"flex items-center justify-between mb-4\">""")
a("""                    <h2 className=\"text-xl font-bold text-white\">范文示例</h2>""")
a("""                    <button onClick={() => setWritingMode('practice')} className=\"btn-primary text-sm\">开始练习</button>""")
a("""                  </div>""")
a("""                  {writingTemplates[selectedTopic]?.examples.map((example, index) => (""")
a("""                    <div key={index} className=\"bg-white/5 rounded-xl overflow-hidden\">""")
a("""                      <button onClick={() => setExpandedExample(expandedExample === index ? null : index)}""")
a("""                        className=\"w-full flex items-center justify-between p-4 text-left hover:bg-white/5 transition-all\">""")
a("""                        <span className=\"text-white font-medium\">{example.title}</span>""")
a("""                        {expandedExample === index ? <ChevronUp className=\"w-5 h-5 text-white/70\" /> : <ChevronDown className=\"w-5 h-5 text-white/70\" />}""")
a("""                      </button>""")
a("""                      {expandedExample === index && (""")
a("""                        <div className=\"px-4 pb-4 animate-fade-in-up\">""")
a("""                          <p className=\"text-white/90 leading-relaxed whitespace-pre-line\">{example.content}</p>""")
a("""                          <button onClick={() => handleCopy(example.content, index + 100)}""")
a("""                            className=\"mt-3 flex items-center gap-2 text-white/70 hover:text-white transition-all\">""")
a("""                            {copiedIndex === index + 100 ? <Check className=\"w-4 h-4\" /> : <Copy className=\"w-4 h-4\" />}""")
a("""                            {copiedIndex === index + 100 ? '已复制' : '复制范文'}""")
a("""                          </button>""")
a("""                        </div>""")
a("""                      )}""")
a("""                    </div>""")
a("""                  ))}""")
a("""                </div>""")
a("""              </div>""")
a("""            </>""")
a("""          ) : (""")
a("""            <div className=\"glass-card p-6\">""")
a("""              <div className=\"flex items-center justify-between mb-4\">""")
a("""                <h2 className=\"text-xl font-bold text-white\">写作练习</h2>""")
a("""                <button onClick={() => { setWritingMode('view'); setScore(null); setUserInput(''); setAiReport(null); }} className=\"text-white/70 hover:text-white\">返回模板</button>""")
a("""              </div>""")
a("""              <div className=\"mb-6 p-4 bg-white/5 rounded-xl\">""")
a("""                <p className=\"text-white/70 mb-1\">主题：</p>""")
a("""                <p className=\"text-white font-medium text-lg\">{writingTemplates[selectedTopic]?.topic}</p>""")
a("""                <p className=\"text-white/50 text-sm mt-2\">要求：至少写 {writingTemplates[selectedTopic]?.topic === '教育' ? '120' : '100'} 词</p>""")
a("""              </div>""")
a("""              <textarea""")
a("""                value={userInput}""")
a("""                onChange={(e) => setUserInput(e.target.value)}""")
a("""                placeholder=\"请在此输入您的作文...\"""")
a("""                className=\"input-glow w-full h-64 resize-none mb-4 font-english\"""")
a("""              />""")
a("""              <div className=\"text-white/50 text-sm mb-4\">字数：{userInput.trim().split(/\\s+/).filter(w => w.length > 0).length} 词</div>""")
a("""""")
a("""              {isAnalyzing && (""")
a("""                <div className=\"mb-4 p-4 bg-white/5 rounded-xl flex items-center gap-3\">""")
a("""                  <div className=\"loader-dots\"><div className=\"loader-dot\" /><div className=\"loader-dot\" /><div className=\"loader-dot\" /></div>""")
a("""                  <span className=\"text-white/70\">AI 正在分析您的作文...</span>""")
a("""                </div>""")
a("""              )}""")
a("""""")
a("""              {!isAnalyzing && score !== null && aiReport && (""")
a("""                <div className=\"mb-6 animate-fade-in-up\">""")
a("""                  {/* Overall Score */}""")
a("""                  <div className={`p-6 bg-gradient-to-r ${scoreBg(score)} rounded-xl mb-4`}>""")
a("""                    <div className=\"flex items-center gap-4 mb-4\">""")
a("""                      <div className={`w-20 h-20 rounded-full bg-gradient-to-r ${scoreBg(score)} border-4 ${score >= 80 ? 'border-green-400' : score >= 60 ? 'border-yellow-400' : 'border-red-400'} flex items-center justify-center`}>""")
a("""                        <span className={`text-3xl font-bold ${scoreColor(score)}`}>{score}</span>""")
a("""                      </div>""")
a("""                      <div>""")
a("""                        <h3 className=\"text-xl font-bold text-white\">总评分</h3>""")
a("""                        <p className=\"text-white/70\">{score >= 80 ? '优秀！文章结构清晰，用词恰当。' : score >= 60 ? '良好！继续努力，注意使用更多连接词。' : '还需努力！建议参考范文，学习更多句型。'}</p>""")
a("""                      </div>""")
a("""                    </div>""")
a("""                    {/* Score Breakdown */}""")
a("""                    <div className=\"grid grid-cols-2 md:grid-cols-5 gap-3\">""")
a("""                      {[['词汇', aiReport.vocabulary], ['语法', aiReport.grammar], ['结构', aiReport.structure], ['连贯', aiReport.coherence], ['篇幅', aiReport.length]].map(([label, val]) => (""")
a("""                        <div key={label} className=\"bg-white/5 rounded-lg p-3 text-center\">""")
a("""                          <p className=\"text-white/50 text-xs\">{label as string}</p>""")
a("""                          <div className=\"mt-1\">""")
a("""                            <div className=\"w-full h-2 bg-white/10 rounded-full overflow-hidden\">""")
a("""                              <div className={`h-full rounded-full transition-all duration-500 ${score >= 80 ? 'bg-green-400' : score >= 60 ? 'bg-yellow-400' : 'bg-red-400'}`} style={{ width: `${(val as number) * 5}%` }} />""")
a("""                            </div>""")
a("""                            <span className={`text-sm font-bold ${scoreColor(val as number)}`}>{val as number}/20</span>""")
a("""                          </div>""")
a("""                        </div>""")
a("""                      ))}""")
a("""                    </div>""")
a("""                  </div>""")
a("""                  {/* Suggestions */}""")
a("""                  <div className=\"bg-white/5 rounded-xl p-4\">""")
a("""                    <h4 className=\"text-white font-medium mb-3 flex items-center gap-2\"><Zap className=\"w-4 h-4 text-yellow-400\" />改进建议</h4>""")
a("""                    <ul className=\"space-y-2\">""")
a("""                      {aiReport.suggestions.map((s, i) => (""")
a("""                        <li key={i} className=\"text-white/70 text-sm flex items-start gap-2\">""")
a("""                          <span className=\"text-accent-400 mt-0.5\">•</span>{s}""")
a("""                        </li>""")
a("""                      ))}""")
a("""                    </ul>""")
a("""                  </div>""")
a("""                </div>""")
a("""              )}""")
a("""""")
a("""              <div className=\"flex gap-4\">""")
a("""                <button onClick={handleReset} className=\"btn-secondary\">重置</button>""")
a("""                <button onClick={handleSubmitWriting} disabled={isAnalyzing || !userInput.trim()}""")
a("""                  className={`btn-primary flex items-center gap-2 ${(!userInput.trim() || isAnalyzing) ? 'opacity-50 cursor-not-allowed' : ''}`}>""")
a("""                  {isAnalyzing ? <div className=\"loader-dot\" /> : <Send className=\"w-4 h-4\" />}""")
a("""                  {isAnalyzing ? '分析中...' : '提交评分'}""")
a("""                </button>""")
a("""              </div>""")
a("""            </div>""")
a("""          )}""")
a("""        </section>""")
a("""      ) : (""")
a("""        <section className=\"px-6\">""")
a("""          {writingMode === 'view' ? (""")
a("""            <div className=\"glass-card p-6\">""")
a("""              <h2 className=\"text-xl font-bold text-white mb-4\">翻译练习</h2>""")
a("""              <div className=\"space-y-4\">""")
a("""                {translationExamples.map((example, index) => (""")
a("""                  <div key={example.id} className=\"bg-white/5 rounded-xl p-4\">""")
a("""                    <div className=\"flex items-center justify-between\">""")
a("""                      <div className=\"flex-1\">""")
a("""                        <p className=\"text-white/70 text-sm mb-1\">中文原文</p>""")
a("""                        <p className=\"text-white text-lg\">{example.chinese}</p>""")
a("""                      </div>""")
a("""                      <button onClick={() => { setSelectedTopic(index); setWritingMode('practice'); setScore(null); setUserInput(''); setAiReport(null); }} className=\"ml-4 btn-primary text-sm\">练习</button>""")
a("""                    </div>""")
a("""                    <div className=\"mt-3\">""")
a("""                      <p className=\"text-white/70 text-sm mb-1\">参考翻译</p>""")
a("""                      <p className=\"text-white font-english\">{example.english}</p>""")
a("""                    </div>""")
a("""                  </div>""")
a("""                ))}""")
a("""              </div>""")
a("""            </div>""")
a("""          ) : (""")
a("""            <div className=\"glass-card p-6\">""")
a("""              <div className=\"flex items-center justify-between mb-4\">""")
a("""                <h2 className=\"text-xl font-bold text-white\">翻译练习</h2>""")
a("""                <button onClick={() => { setWritingMode('view'); setScore(null); setUserInput(''); setAiReport(null); }} className=\"text-white/70 hover:text-white\">返回列表</button>""")
a("""              </div>""")
a("""              <div className=\"mb-6 p-4 bg-white/5 rounded-xl\">""")
a("""                <p className=\"text-white/70 text-sm mb-2\">中文原文</p>""")
a("""                <p className=\"text-white text-lg\">{translationExamples[selectedTopic]?.chinese}</p>""")
a("""              </div>""")
a("""              <textarea""")
a("""                value={userInput}""")
a("""                onChange={(e) => setUserInput(e.target.value)}""")
a("""                placeholder=\"请输入英文翻译...\"""")
a("""                className=\"input-glow w-full h-48 resize-none mb-4 font-english\"""")
a("""              />""")
a("""              <div className=\"text-white/50 text-sm mb-4\">字数：{userInput.trim().split(/\\s+/).filter(w => w.length > 0).length} 词</div>""")
a("""""")
a("""              {isAnalyzing && (""")
a("""                <div className=\"mb-4 p-4 bg-white/5 rounded-xl flex items-center gap-3\">""")
a("""                  <div className=\"loader-dots\"><div className=\"loader-dot\" /><div className=\"loader-dot\" /><div className=\"loader-dot\" /></div>""")
a("""                  <span className=\"text-white/70\">正在分析翻译质量...</span>""")
a("""                </div>""")
a("""              )}""")
a("""""")
a("""              {!isAnalyzing && score !== null && aiReport && (""")
a("""                <div className=\"mb-6 animate-fade-in-up\">""")
a("""                  <div className={`p-6 bg-gradient-to-r ${scoreBg(score)} rounded-xl mb-4`}>""")
a("""                    <div className=\"flex items-center gap-4 mb-4\">""")
a("""                      <div className={`w-20 h-20 rounded-full border-4 flex items-center justify-center ${score >= 80 ? 'border-green-400' : score >= 60 ? 'border-yellow-400' : 'border-red-400'}`}>""")
a("""                        <span className={`text-3xl font-bold ${scoreColor(score)}`}>{score}</span>""")
a("""                      </div>""")
a("""                      <div>""")
a("""                        <h3 className=\"text-xl font-bold text-white\">翻译评分</h3>""")
a("""                        <p className=\"text-white/70\">{score >= 80 ? '翻译准确，表达流畅！' : score >= 60 ? '基本准确，注意细节。' : '需要改进，对比参考答案。'}</p>""")
a("""                      </div>""")
a("""                    </div>""")
a("""                    <div className=\"grid grid-cols-2 md:grid-cols-5 gap-3\">""")
a("""                      {[['词汇', aiReport.vocabulary], ['语法', aiReport.grammar], ['结构', aiReport.structure], ['连贯', aiReport.coherence], ['篇幅', aiReport.length]].map(([label, val]) => (""")
a("""                        <div key={label} className=\"bg-white/5 rounded-lg p-3 text-center\">""")
a("""                          <p className=\"text-white/50 text-xs\">{label as string}</p>""")
a("""                          <div className=\"mt-1\">""")
a("""                            <div className=\"w-full h-2 bg-white/10 rounded-full overflow-hidden\">""")
a("""                              <div className={`h-full rounded-full transition-all duration-500 ${score >= 80 ? 'bg-green-400' : score >= 60 ? 'bg-yellow-400' : 'bg-red-400'}`} style={{ width: `${(val as number) * 5}%` }} />""")
a("""                            </div>""")
a("""                            <span className={`text-sm font-bold ${scoreColor(val as number)}`}>{val as number}/20</span>""")
a("""                          </div>""")
a("""                        </div>""")
a("""                      ))}""")
a("""                    </div>""")
a("""                  </div>""")
a("""                  <div className=\"bg-white/5 rounded-xl p-4 mb-4\">""")
a("""                    <p className=\"text-white/70 text-sm mb-1\">参考翻译</p>""")
a("""                    <p className=\"text-white font-english\">{translationExamples[selectedTopic]?.english}</p>""")
a("""                  </div>""")
a("""                  <div className=\"bg-white/5 rounded-xl p-4\">""")
a("""                    <h4 className=\"text-white font-medium mb-2 flex items-center gap-2\"><Zap className=\"w-4 h-4 text-yellow-400\" />建议</h4>""")
a("""                    {aiReport.suggestions.map((s, i) => (""")
a("""                      <p key={i} className=\"text-white/70 text-sm\">{s}</p>""")
a("""                    ))}""")
a("""                  </div>""")
a("""                </div>""")
a("""              )}""")
a("""""")
a("""              <div className=\"flex gap-4\">""")
a("""                <button onClick={handleReset} className=\"btn-secondary\">重置</button>""")
a("""                <button onClick={handleSubmitTranslation} disabled={isAnalyzing || !userInput.trim()}""")
a("""                  className={`btn-primary flex items-center gap-2 ${(!userInput.trim() || isAnalyzing) ? 'opacity-50 cursor-not-allowed' : ''}`}>""")
a("""                  {isAnalyzing ? <div className=\"loader-dot\" /> : <Send className=\"w-4 h-4\" />}""")
a("""                  {isAnalyzing ? '分析中...' : '提交评分'}""")
a("""                </button>""")
a("""              </div>""")
a("""            </div>""")
a("""          )}""")
a("""        </section>""")
a("""      )}""")
a("""    </div>""")
a("""  );""")
a("""};""")

with open('src/pages/Writing.tsx', 'w', encoding='utf-8') as f:
    f.write('\\n'.join(lines) + '\\n')
print('Done: Writing.tsx rewritten with improved AI scoring')
