import sys

lines = []
a = lines.append

a("import { useEffect, useState } from 'react';")
a("import { BookOpen, Headphones, FileText, PenTool, FileQuestion, Gamepad2, Flame, Clock, Award, ChevronRight, Calendar, ArrowRight, AlertCircle, Brain, TrendingUp, BarChart3 } from 'lucide-react';")
a("import { useAppStore, useAuthStore } from '../store/useAppStore';")
a("import { ProgressRing } from '../components/ProgressRing';")
a("import { useNavigate } from 'react-router-dom';")
a("")
a("const quickAccessItems = [")
a("  { id: '/words', label: '单词学习', icon: BookOpen, color: 'from-primary-500 to-primary-600' },")
a("  { id: '/review', label: '艾宾浩斯复习', icon: Brain, color: 'from-purple-500 to-pink-500' },")
a("  { id: '/listening', label: '听力训练', icon: Headphones, color: 'from-accent-500 to-accent-600' },")
a("  { id: '/reading', label: '阅读练习', icon: FileText, color: 'from-green-500 to-green-600' },")
a("  { id: '/writing', label: '写作翻译', icon: PenTool, color: 'from-yellow-500 to-orange-500' },")
a("  { id: '/exam', label: '真题模拟', icon: FileQuestion, color: 'from-blue-500 to-blue-600' },")
a("  { id: '/games', label: '互动游戏', icon: Gamepad2, color: 'from-purple-500 to-purple-600' },")
a("];")
a("")
a("const moduleMap: Record<string, string> = {")
a("  words: '/words',")
a("  listening: '/listening',")
a("  reading: '/reading',")
a("  writing: '/writing',")
a("  exam: '/exam',")
a("  review: '/profile',")
a("};")
a("")
a("export const Home = () => {")
a("  const { userProgress, todayTasks, checkIn, isFirstTime, setIsFirstTime, wrongBook, getReviewStats, history } = useAppStore();")
a("  const { currentUser } = useAuthStore();")
a("  const [isCheckedIn, setIsCheckedIn] = useState(false);")
a("  const [showConfetti, setShowConfetti] = useState(false);")
a("  const navigate = useNavigate();")
a("")
a("  const wrongBookCount = wrongBook.length;")
a("  const reviewStats = getReviewStats();")
a("  const totalReviewWords = reviewStats.overdue + reviewStats.today;")
a("")
a("  useEffect(() => {")
a("    const today = new Date().toISOString().split('T')[0];")
a("    setIsCheckedIn(userProgress.lastCheckInDate === today);")
a("  }, [userProgress.lastCheckInDate]);")
a("")
a("  useEffect(() => {")
a("    if (isFirstTime) {")
a("      setTimeout(() => setIsFirstTime(false), 5000);")
a("    }")
a("  }, [isFirstTime, setIsFirstTime]);")
a("")
a("  const handleCheckIn = () => {")
a("    checkIn();")
a("    setIsCheckedIn(true);")
a("    setShowConfetti(true);")
a("    setTimeout(() => setShowConfetti(false), 2000);")
a("  };")
a("")
a("  const handleTaskClick = (module: string) => {")
a("    const path = moduleMap[module];")
a("    if (path) navigate(path);")
a("  };")
a("")
a("  const progressPercent = Math.min(100, (userProgress.learnedWords / 2000) * 100);")
a("  const completedTasks = todayTasks.filter((t) => t.completed).length;")
a("  const totalTasks = todayTasks.length;")
a("")
a("  // 7-day study trend chart")
a("  const studyTrend = history.length >= 7 ? history.slice(-7) : history;")
a("  const maxMinutes = Math.max(...studyTrend.map((h) => h.minutes), 1);")
a("  const chartWidth = 400;")
a("  const chartHeight = 120;")
a("  const padding = { top: 10, right: 10, bottom: 25, left: 30 };")
a("  const innerWidth = chartWidth - padding.left - padding.right;")
a("  const innerHeight = chartHeight - padding.top - padding.bottom;")
a("")
a("  const points = studyTrend.map((h, i) => {")
a("    const x = padding.left + (i / Math.max(studyTrend.length - 1, 1)) * innerWidth;")
a("    const y = padding.top + innerHeight - (h.minutes / maxMinutes) * innerHeight;")
a("    return { x, y, ...h };")
a("  });")
a("")
a("  const polyline = points.map((p) => `${p.x},${p.y}`).join(' ');")
a("  const areaPath = points.length > 0")
a("    ? `M${points[0].x},${padding.top + innerHeight} ${points.map((p) => `L${p.x},${p.y}`).join(' ')} L${points[points.length - 1].x},${padding.top + innerHeight} Z`")
a("    : '';")
a("")
a("  return (")
a('    <div className="min-h-screen pb-24 md:pb-0 animate-fade-in-up">')
a("      {isFirstTime && (")
a('        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center animate-fade-in">')
a('          <div className="glass-card p-8 max-w-md mx-4 text-center animate-bounce-in">')
a('            <h2 className="text-2xl font-bold text-white mb-4">欢迎使用四级英语学习应用！</h2>')
a('            <p className="text-white/80 mb-6">开始您的英语学习之旅，每天进步一点点</p>')
a('            <button onClick={() => setIsFirstTime(false)} className="btn-primary">开始学习</button>')
a('          </div>')
a('        </div>')
a("      )}")
a("")
a('      <header className="p-6 mb-6">')
a('        <div className="flex justify-between items-center">')
a("          <div>")
a('            <h1 className="text-3xl font-bold text-white">')
a("              {new Date().getHours() < 12 ? '早上好' : new Date().getHours() < 18 ? '下午好' : '晚上好'}，{currentUser?.username || '学习者'}！")
a("            </h1>")
a('            <p className="text-white/70 mt-1">今天也要加油学习哦！</p>')
a("          </div>")
a("          <button")
a("            onClick={handleCheckIn}")
a("            disabled={isCheckedIn}")
a("            className={`relative flex items-center gap-2 px-6 py-3 rounded-full transition-all duration-300 ${")
a("              isCheckedIn")
a("                ? 'bg-green-500/30 text-green-300 cursor-not-allowed'")
a("                : 'bg-gradient-to-r from-orange-500 to-red-500 text-white hover:shadow-lg hover:-translate-y-1'")
a("            }`}")
a("          >")
a('            <Calendar className="w-5 h-5" />')
a("            {isCheckedIn ? '已打卡' : '今日打卡'}")
a("            {showConfetti && (")
a('              <div className="absolute inset-0 flex items-center justify-center">')
a("                {[...Array(20)].map((_, i) => (")
a("                  <span key={i} className=\"confetti-piece\" style={{ backgroundColor: ['#f093fb', '#f5576c', '#667eea', '#ec4899'][i % 4], left: `${Math.random() * 100}%`, animationDelay: `${Math.random() * 0.5}s` }} />")
a("                ))}")
a("              </div>")
a("            )}")
a("          </button>")
a("        </div>")
a("      </header>")
a("")
a('      <section className="px-6 mb-8">')
a('        <div className="glass-card p-6">')
a('          <div className="flex flex-col md:flex-row items-center justify-between gap-6">')
a('            <div className="flex gap-8">')
a('              <ProgressRing progress={progressPercent} label="已学单词" value={`${userProgress.learnedWords}/2000`} />')
a('              <ProgressRing progress={(userProgress.todayStudyTime / 60) * 100} label="今日学习" value={`${userProgress.todayStudyTime}分钟`} />')
a('              <ProgressRing progress={userProgress.streakDays * 10} label="连续打卡" value={`${userProgress.streakDays}天`} />')
a('            </div>')
a('            <div className="flex items-center gap-4">')
a('              <div className="flex items-center gap-2 text-white/70">')
a('                <Flame className="w-6 h-6 text-orange-400" /><span>连续 {userProgress.streakDays} 天</span>')
a('              </div>')
a('              <div className="flex items-center gap-2 text-white/70">')
a('                <Clock className="w-6 h-6 text-blue-400" /><span>累计 {userProgress.totalStudyTime} 分钟</span>')
a('              </div>')
a('              <div className="flex items-center gap-2 text-white/70">')
a('                <Award className="w-6 h-6 text-yellow-400" /><span>已掌握 {userProgress.learnedWords} 词</span>')
a('              </div>')
a('            </div>')
a('          </div>')
a('        </div>')
a('      </section>')
a("")
a('      {studyTrend.length > 0 && (')
a('        <section className="px-6 mb-8">')
a('          <div className="glass-card p-6">')
a('            <div className="flex items-center gap-2 mb-4">')
a('              <TrendingUp className="w-5 h-5 text-accent-400" />')
a('              <h2 className="text-lg font-bold text-white">近 {studyTrend.length} 天学习趋势</h2>')
a('            </div>')
a('            <div className="overflow-x-auto">')
a('              <svg viewBox={`0 0 ${chartWidth} ${chartHeight}`} className="w-full max-w-lg mx-auto" preserveAspectRatio="xMidYMid meet">')
a('                <defs>')
a('                  <linearGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1">')
a('                    <stop offset="0%" stopColor="#667eea" stopOpacity="0.3" />')
a('                    <stop offset="100%" stopColor="#667eea" stopOpacity="0.02" />')
a('                  </linearGradient>')
a('                </defs>')
a("                {[0, 0.25, 0.5, 0.75, 1].map((frac) => (")
a("                  <g key={frac}>")
a('                    <line x1={padding.left} y1={padding.top + innerHeight * (1 - frac)} x2={chartWidth - padding.right} y2={padding.top + innerHeight * (1 - frac)} stroke="rgba(255,255,255,0.08)" strokeDasharray="4,4" />')
a("                    <text x={padding.left - 5} y={padding.top + innerHeight * (1 - frac) + 4} fill=\"rgba(255,255,255,0.4)\" fontSize=\"9\" textAnchor=\"end\">{Math.round(maxMinutes * frac)}m</text>")
a("                  </g>")
a("                ))}")
a('                {areaPath && <path d={areaPath} fill="url(#areaGrad)" />}')
a('                <polyline points={polyline} fill="none" stroke="#667eea" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />')
a("                {points.map((p, i) => (")
a("                  <g key={i}>")
a('                    <circle cx={p.x} cy={p.y} r="4" fill="#667eea" stroke="white" strokeWidth="2" />')
a('                    <text x={p.x} y={chartHeight - 4} fill="rgba(255,255,255,0.5)" fontSize="8" textAnchor="middle">{p.date.slice(5)}</text>')
a('                    <text x={p.x} y={p.y - 10} fill="rgba(255,255,255,0.7)" fontSize="8" textAnchor="middle">{p.minutes}m</text>')
a("                  </g>")
a("                ))}")
a("              </svg>")
a("            </div>")
a("            <div className=\"flex justify-around mt-4 text-center\">")
a('              <div className="bg-white/5 rounded-lg px-4 py-2">')
a('                <p className="text-white/50 text-xs">日均学习</p>')
a('                <p className="text-white font-bold text-lg">{Math.round(studyTrend.reduce((a, b) => a + b.minutes, 0) / studyTrend.length)} 分钟</p>')
a('              </div>')
a('              <div className="bg-white/5 rounded-lg px-4 py-2">')
a('                <p className="text-white/50 text-xs">共学单词</p>')
a('                <p className="text-white font-bold text-lg">{studyTrend.reduce((a, b) => a + b.wordsLearned, 0)} 个</p>')
a('              </div>')
a('              <div className="bg-white/5 rounded-lg px-4 py-2">')
a('                <p className="text-white/50 text-xs">复习单词</p>')
a('                <p className="text-white font-bold text-lg">{studyTrend.reduce((a, b) => a + b.wordsReviewed, 0)} 个</p>')
a('              </div>')
a('            </div>')
a('          </div>')
a('        </section>')
a('      )}')
a("")
a('      <section className="px-6 mb-8">')
a('        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">')
a('          <BookOpen className="w-6 h-6 text-accent-400" />今日任务')
a('          <span className="text-sm font-normal text-white/50">({completedTasks}/{totalTasks})</span>')
a('        </h2>')
a('        <div className="glass-card p-4 space-y-4">')
a("          {todayTasks.map((task, index) => (")
a("            <div key={task.id} className=\"flex items-center gap-4 p-4 bg-white/5 rounded-xl hover:bg-white/10 transition-all cursor-pointer\" style={{ animationDelay: `${index * 0.1}s` }} onClick={() => handleTaskClick(task.module)}>")
a("              <div className={`w-6 h-6 rounded-full flex items-center justify-center ${task.completed ? 'bg-green-500' : 'bg-white/20'}`}>")
a("                {task.completed && <span className=\"text-white text-sm\">✓</span>}")
a("              </div>")
a("              <div className=\"flex-1\">")
a("                <p className={`font-medium ${task.completed ? 'text-white/50 line-through' : 'text-white'}`}>{task.title}</p>")
a('                <div className="w-full h-2 bg-white/10 rounded-full mt-2 overflow-hidden">')
a('                  <div className="h-full progress-flow rounded-full transition-all duration-1000" style={{ width: `${(task.progress / task.target) * 100}%` }} />')
a("                </div>")
a("              </div>")
a("              <div className=\"flex items-center gap-2\">")
a('                <span className="text-white/50 text-sm">{task.progress}/{task.target}</span>')
a("                <ArrowRight className={`w-5 h-5 ${task.completed ? 'text-white/30' : 'text-white/50'} />} />")
a("              </div>")
a("            </div>")
a("          ))}")
a("        </div>")
a("      </section>")
a("")
a("      {wrongBookCount > 0 && (")
a('        <section className="px-6 mb-8">')
a("          <button onClick={() => navigate('/profile')} className=\"w-full glass-card p-6 bg-gradient-to-r from-red-500/20 to-orange-500/20 border border-red-500/30 hover:border-red-500/50 transition-all group\">")
a('            <div className="flex items-center justify-between">')
a('              <div className="flex items-center gap-4">')
a('                <div className="w-14 h-14 rounded-full bg-gradient-to-r from-red-500 to-orange-500 flex items-center justify-center">')
a('                  <AlertCircle className="w-7 h-7 text-white" />')
a('                </div>')
a('                <div className="text-left">')
a('                  <h3 className="text-xl font-bold text-white mb-1">错题本</h3>')
a('                  <p className="text-white/70">有<span className="text-red-400 font-bold text-lg">{wrongBookCount}</span> 个单词需要复习</p>')
a('                </div>')
a('              </div>')
a('              <div className="flex items-center gap-3">')
a('                <span className="px-4 py-2 bg-red-500/30 text-red-300 rounded-lg font-medium">立即复习</span>')
a('                <ChevronRight className="w-6 h-6 text-white/50 group-hover:text-white group-hover:translate-x-1 transition-all" />')
a('              </div>')
a('            </div>')
a('          </button>')
a('        </section>')
a('      )}')
a("")
a("      {totalReviewWords > 0 && (")
a('        <section className="px-6 mb-8">')
a("          <button onClick={() => navigate('/review')} className=\"w-full glass-card p-6 bg-gradient-to-r from-purple-500/20 to-pink-500/20 border border-purple-500/30 hover:border-purple-500/50 transition-all group\">")
a('            <div className="flex items-center justify-between">')
a('              <div className="flex items-center gap-4">')
a('                <div className="w-14 h-14 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center">')
a('                  <Brain className="w-7 h-7 text-white" />')
a('                </div>')
a('                <div className="text-left">')
a('                  <h3 className="text-xl font-bold text-white mb-1">艾宾浩斯复习</h3>')
a('                  <p className="text-white/70">')
a('                    {reviewStats.overdue > 0 && <span>逾期 <span className="text-red-400 font-bold text-lg">{reviewStats.overdue}</span> 个单词</span>}')
a('                    {reviewStats.overdue > 0 && reviewStats.today > 0 && <span>，</span>}')
a('                    {reviewStats.today > 0 && <span>今日待复习<span className="text-purple-400 font-bold text-lg">{reviewStats.today}</span> 个</span>}')
a('                  </p>')
a('                </div>')
a('              </div>')
a('              <div className="flex items-center gap-3">')
a('                <span className="px-4 py-2 bg-purple-500/30 text-purple-300 rounded-lg font-medium">开始复习</span>')
a('                <ChevronRight className="w-6 h-6 text-white/50 group-hover:text-white group-hover:translate-x-1 transition-all" />')
a('              </div>')
a('            </div>')
a('          </button>')
a('        </section>')
a('      )}')
a("")
a('      <section className="px-6">')
a('        <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">')
a('          <Gamepad2 className="w-6 h-6 text-accent-400" />快速入口')
a('        </h2>')
a('        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">')
a("          {quickAccessItems.map((item, index) => {")
a("            const Icon = item.icon;")
a("            return (")
a("              <button key={item.id} onClick={() => navigate(item.id)} className=\"glass-card p-6 flex flex-col items-center gap-3 card-hover\" style={{ animationDelay: `${index * 0.1}s` }}>")
a("                <div className={`w-12 h-12 rounded-full bg-gradient-to-r ${item.color} flex items-center justify-center`}>")
a("                  <Icon className=\"w-6 h-6 text-white\" />")
a("                </div>")
a("                <span className=\"text-white font-medium\">{item.label}</span>")
a('                <ChevronRight className="w-4 h-4 text-white/50" />')
a("              </button>")
a("            );")
a("          })}")
a("        </div>")
a("      </section>")
a("    </div>")
a("  );")
a("};")

with open('src/pages/Home.tsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('Done: Home.tsx written with UTF-8 encoding')
